### ISSUE TITLE
Log printing format

### ISSUE THREAD

**Issue by hsson** [kandidat-highlights/model#6]
Format the log that gets printed into CSV format. Let every parameter be a column in a CSV, where empty parameters are blank columns in the CSV. 

The purpose of this is to make it easy to append experimentation results.

**Comment by almenjonatan** [comment]
Set date and time for each run.

**Comment by Mxiim** [comment]
Log highest F1 from validation, log when it happened (epoch) and recall, precision during that epoch for training and validation. Log everything to same file.

**Comment by hsson** [comment]
Solved by pull request #14
